apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx
          name: demovolume
  volumes:
    - name: demovolume
      persistentVolumeClaim:
        claimName: demo-pvc
